toolbar:
  - styleselect | bold italic | undo redo | alignleft aligncenter alignright alignjustify
  - bullist numlist outdent indent | uploadimage | link
plugins:
  - uploadimage
  - link
selector: 'textarea.tinymce'
